"""
attribution_builder.py — Build the collapsible <details> attribution footer.

Contains:
  - Generator version + timestamp
  - Image attribution table (source, license, author per image)
  - Cultural events auto-discovery disclaimer
  - Generator credit line
"""
from __future__ import annotations
import datetime
from typing import Any

GENERATOR_VERSION = "1.0.0"
GENERATOR_URL = "https://github.com/flysoftware-git/road-trip-generator"


class AttributionBuilder:
    def build(self, trip: dict[str, Any]) -> str:
        timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        rows = self._image_table_rows(trip)
        image_table = self._image_table(rows) if rows else "<p>No image attribution data available.</p>"
        return (
            '<details id="attribution-block" style="margin-top:3rem;padding:1.5rem;'
            'background:#f5f5f5;border-radius:8px;font-size:0.85rem;color:#555;">\n'
            f'  <summary style="font-weight:600;cursor:pointer;font-size:1rem;">'
            f'Attribution &amp; Version Information</summary>\n'
            f'  <div style="margin-top:1rem;">\n'
            f'    <p><strong>Generator:</strong> Road Trip Itinerary Generator v{GENERATOR_VERSION}<br>\n'
            f'    <strong>Generated:</strong> {timestamp}<br>\n'
            f'    <strong>Trip:</strong> {trip["trip"].get("title", "")}</p>\n'
            f'    <h4 style="margin-top:1.5rem;">Image Credits</h4>\n'
            f'    {image_table}\n'
            f'    <h4 style="margin-top:1.5rem;">Cultural Events Disclaimer</h4>\n'
            f'    <p>Event information was auto-discovered via web search and AI synthesis. '
            f'Dates, venues, and admission details may have changed. Always verify with '
            f'official sources before attending.</p>\n'
            f'    <h4 style="margin-top:1.5rem;">Generator Credit</h4>\n'
            f'    <p>This itinerary was generated by the '
            f'<a href="{GENERATOR_URL}" target="_blank">Road Trip Itinerary Generator</a> '
            f'— an open-source tool that combines AI content generation, live web search, '
            f'and verified URLs to produce self-contained trip guides. '
            f'Content is AI-generated and should be verified independently.</p>\n'
            f'  </div>\n'
            f'</details>\n'
        )

    def _image_table_rows(self, trip: dict[str, Any]) -> list[dict[str, str]]:
        rows = []
        for dest in trip.get("destinations", []):
            for img in dest.get("images", []):
                rows.append({
                    "destination": dest["name"],
                    "title": img.get("title", "Untitled"),
                    "source": img.get("source", ""),
                    "credit": img.get("credit", ""),
                    "license": img.get("license", ""),
                })
        return rows

    def _image_table(self, rows: list[dict[str, str]]) -> str:
        html = (
            '<table style="width:100%;border-collapse:collapse;font-size:0.8rem;">\n'
            '  <thead><tr style="background:#e0e0e0;">'
            '<th style="padding:4px 8px;text-align:left;">Destination</th>'
            '<th style="padding:4px 8px;text-align:left;">Image</th>'
            '<th style="padding:4px 8px;text-align:left;">Source</th>'
            '<th style="padding:4px 8px;text-align:left;">Credit</th>'
            '<th style="padding:4px 8px;text-align:left;">License</th>'
            '</tr></thead>\n<tbody>\n'
        )
        for i, row in enumerate(rows):
            bg = "#fafafa" if i % 2 == 0 else "#ffffff"
            html += (
                f'  <tr style="background:{bg};">'
                f'<td style="padding:4px 8px;">{row["destination"]}</td>'
                f'<td style="padding:4px 8px;">{row["title"]}</td>'
                f'<td style="padding:4px 8px;">{row["source"]}</td>'
                f'<td style="padding:4px 8px;">{row["credit"]}</td>'
                f'<td style="padding:4px 8px;">{row["license"]}</td>'
                f'</tr>\n'
            )
        html += '</tbody>\n</table>\n'
        return html
